### ISSUE TITLE
 Delivery Status Notifications do not work

### ISSUE THREAD

**Issue by vassad** [jeboehm/docker-mailserver#131]
**Describe the bug**
Delivery Status Notifications are not sent when prompted to - moveover, this functionality existed, but removed by a certain decision here:  
https://github.com/jeboehm/docker-mailserver/commit/6f03098152f9230828f8eb52891a90f3b7dd25e5

I understand, how to enable it back, but: **why was it removed, is it unsafe? If yes - then why?**
BTW, this project is perfect - i finally ended up using _nämlich_ this one due to easy to use, fullstack and fancy interface, very convenient especially with many domains and users :)

**To Reproduce**
Write the message, select "Notify on delivery" and send the message to a valid receiver.

**Expected behavior**
To receive the Notification mail, as it comes within

**Comment by jeboehm** [comment]
> BTW, this project is perfect - i finally ended up using nämlich this one due to easy to use, fullstack and fancy interface, very convenient especially with many domains and users :)
I'm glad to hear that! Thank you! :-)

The decision to remove DSNs was a little opinionated but I think it is not a good idea to automatically inform a sender about successful delivery because that might leak information about existing email addresses or the reactiveness of your infrastructure - maybe to spammers or attackers. Be aware that this only affects Successful-DSNs. Delivery failures will be bounced as before.
