### ISSUE TITLE
Can i have a option when server host provier blocked outgoing with port 25?

### ISSUE THREAD

**Issue by jc01rho** [jeboehm/docker-mailserver#203]
```
<[---@naver.com](mailto:---@naver.com)>: connect to mx2.naver.com[125.209.238.137]:25: Operation
    timed out
Reporting-MTA: dns; mail.yangminnomad.co.kr
X-Postfix-Queue-ID: AA82318063C
X-Postfix-Sender: rfc822; [admin@domain.tld](mailto:admin@domain.tld)
Arrival-Date: Mon, 18 Jul 2022 17:44:43 +0000 (UTC)

Final-Recipient: rfc822; [---@naver.com](mailto:---@naver.com)
Original-Recipient: rfc822;[---@naver.com](mailto:---@naver.com)
Action: failed
Status: 4.4.1
Diagnostic-Code: X-Postfix; connect to mx2.naver.com[125.209.238.137]:25:
    Operation timed out
```

cause the mailserver setted int oracle free tier cloud,
https://support.oracle.com/knowledge/Oracle%20Cloud/2787393_1.html

can i have solution for sending mail?

**Comment by agittins** [comment]
The wiki has an answer that should solve this for you:
https://github.com/jeboehm/docker-mailserver/wiki/Howto:-Use-External-Mail-Relay-For-Sending-Mails

You'll need to have a mail server that will accept your outbound mail on port 465 or 587, per the oracle doc you mentioned. It might be more complicated if you need authentication, but hopefully that's helpful as a starting point.

**Comment by jc01rho** [comment]
but when i try to send a mail (with, /webmail ),  trying to connect 25,
how can i tell to my mailserver to trying port 587 but 25,  currntly tring "  mx2.naver.com[125.209.238.137]:25: "

**Comment by agittins** [comment]
I think the simplest answer, for 99% of situations is:

It is impossible to host your own mail server _completely_ for free.

This is because any free methods will be used by spammers, so then everyone blocks mail coming from free services.

At some point, your email must pass through a service that you pay for. That might be by hosting your mailserver on a paid service (like google, amazon, linode or oracle non-free etc), or by paying for a mail relay service (like your ISP, or sendgrid, mailgun etc).

If you are not paying for any services, you cannot go further. If you **are** paying for something, tell us what and perhaps we can work out how to send your mail through it (using the instructions I gave above).

Does that make sense? I hope I am describing in a way that is clear.

**Comment by jc01rho** [comment]
thx for clarify.  fully understood.

and especially metioning sendgrid, mailgun
