### ISSUE TITLE
What are the requierements for running this?

### ISSUE THREAD

**Issue by pluim003** [jeboehm/docker-mailserver#225]
Yesterday tried installing docker-mailserver on my Raspberry Pi4 with 4GB of RAM and with some other containers active. After installation through git clone ...  and docker-compose up -d after modifying .env my Pi got totally unresponsive and had to pull the plug and restart it. Before everything was started issue the docker-compose down.

This morning I gave it another try. Thought that also port 81 might interfere with my nginx-container, so in docker-compose.production.yml changed that to 82. After recreating the containers the same happened and Pi was unresponsive again.

Would like to use my own mailserver but unfortunately currently it's not working.

Thanx in advance.

**Comment by jeboehm** [comment]
I've never tested it on the Pi. Mainly, because you'll need a persistent IP address to deliver mails to other hosts.
When I look into the resource usage of the containers I see that the (anti) virus container has a heavy memory usage of > 1 GB on my setup.
You could test if it works better when you disable the malware protection: https://github.com/jeboehm/docker-mailserver/wiki/Howto:-Disable-Malware-Scanning

**Comment by pluim003** [comment]
Thanx. 1GB is indeed quite a lot. From the 4GB memory about 60% is in use currently. 
Well I have a persistent ip-address. Some of my internal running sites are simply reachable from the outside, so that shouldn't be a problem. I'll dig into this later with disabling the malware protection.
