### ISSUE TITLE
SSL port 465

### ISSUE THREAD

**Issue by Montereytony** [jeboehm/docker-mailserver#55]
Great project, I was able to get a server up quickly by just following your instructions. Any chance you can add ssl to the smtp protocol.   I tested with  the opera mail client and could not relay email, I assume it is because starttls option is not available or I do not know how to configure it.

**Comment by jeboehm** [comment]
Hi @Montereytony 
good to hear that!
TLS is supported on IMAP, POP3 and even SMTP with STARTTLS.

Make sure that you have disabled SSL, enabled STARTTLS and that you use port 25 for SMTP.

**Comment by rover886** [comment]
@jeboehm Really a great project. By following README instructions I could able to up the server. 

Everything works really fine, I tested IMAP(S), POP3(S) and Mail Submission as well. 

But I have an requirement where I wanted to test an email client with legacy SMTPS protocol instead of using the STARTTLS command", i.e. with port 465. So is it possible to enable SMTP over 465 without STARTTLS command.
